remote_theme: daattali/beautiful-jekyll
#remote_theme: just-the-docs/just-the-docs

title: Passwordless

author: Arnaud Dagnelies

navbar-links:
  Usage: usage
  Webauthn Guide:
    - Introduction: webauthn-guide/1_introduction
    - Regsitration: webauthn-guide/2_registration
    - Authentication: webauthn-guide/3_authentication
  Security & Privacy FAQ: security
  Thoughts: thoughts

kramdown:
  input: GFM

navbar-col: "#7957d5"
navbar-text-col: "#fff"
navbar-border-col: "#7957d5"

page-col: "#fff"
text-col: "#000"
link-col: "#7957d5"
hover-col: "#f2effb"

footer-col: "#f2effb"
footer-text-col: "#552fbc"
footer-link-col: "#7957d5"
footer-hover-col: "#000"
