#remote_theme: dagnelies/beautiful-jekyll
remote_theme: daattali/beautiful-jekyll
#remote_theme: just-the-docs/just-the-docs

title: Passwordless

author: Arnaud Dagnelies

navbar-var-length: true

navbar-links:
  Demo:
    - Live: https://passwordless-id.github.io/demo/
    - Source: https://github.com/passwordless-id/demo
  Pricing: pricing
  Webauthn:
    - Introduction: protocols/webauthn/1_introduction
    - Helper Library: https://github.com/passwordless-id/webauthn
    - Playground: https://webauthn.passwordless.id/demos/playground.html
    - Registration: protocols/webauthn/2_registration
    - Authentication: protocols/webauthn/3_authentication
    - Security & Privacy: protocols/webauthn/4_security
    - E-Mails vs Usernames: thoughts/emails-vs-usernames
    - User Guidance: thoughts/guidance
#  Protocols:
#    OAuth2 / OpenID:
#      - Introduction: protocols/oauth2/1_introduction    
    


edit_page_button: true

#light: "#d4fbff"
#medium: "#6dc9f7"
#dark: "#0089ef"

navbar-col: "#0089ef"
navbar-text-col: "#fff"
navbar-border-col: "#0089ef"

page-col: "#fff"
text-col: "#000"
link-col: "#0089ef"
hover-col: "#6dc9f7"

footer-col: "#ffd7e5"
footer-text-col: "#fa759e"


#navbar-col: "#7957d5"
#navbar-text-col: "#fff"
#navbar-border-col: "#7957d5"

#page-col: "#fff"
#text-col: "#000"
#link-col: "#7957d5"
#hover-col: "#f2effb"

#footer-col: "#f2effb"
#footer-text-col: "#552fbc"
#footer-link-col: "#7957d5"
#footer-hover-col: "#000"
