remote_theme: dagnelies/beautiful-jekyll
#remote_theme: daattali/beautiful-jekyll
#remote_theme: just-the-docs/just-the-docs

title: Passwordless

author: Arnaud Dagnelies

navbar-links:
  Playground: playground.html
  Usage:
    - Introduction: usage/1_introduction
    - JS Helper library: usage/2_js
  Webauthn Guide:
    - Introduction: webauthn/1_introduction
    - Registration: webauthn/2_registration
    - Authentication: webauthn/3_login
    - Security & Privacy: webauthn/4_security
  Thoughts: 
    - E-Mails vs Usernames: thoughts/emails-vs-usernames
    - User Guidance: thoughts/guidance


edit_page_button: true

navbar-col: "#7957d5"
navbar-text-col: "#fff"
navbar-border-col: "#7957d5"

page-col: "#fff"
text-col: "#000"
link-col: "#7957d5"
hover-col: "#f2effb"

footer-col: "#f2effb"
footer-text-col: "#552fbc"
footer-link-col: "#7957d5"
footer-hover-col: "#000"
